### ISSUE TITLE
sort out required and optional dependencies and separate test coverage accordingly

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#105]
`setup.py` makes a distinction between required and optional dependencies. So if one has all the required dependencies, the installation completes without an error. However, there is no such distinction in tests. After a successful installation, proceeding with tests typically results in a bunch of errors (mostly due to lack of some optional dependencies). This is quite confusing for new users. 

Maybe we should divide the tests into two: `-core` and `-all`, where `./run_tests.py -core` will run tests that can be run only with the required dependencies.

We might also want to consider revising what is required and what is optional (maybe no need to declare pure python dependencies `setup.py` can install automatically as optional).

Related issue: #48

**Comment by slivingston** [comment]
A predicated test suite driven by `run_tests.py` is implemented as of cdfb3d6c62a3773aa9b99a16d8611bc615b1910a. Documentation appears in the README, the User's Guide, and `run_tests.py -h`.

In particular, note that `./run_tests.py` should always pass. It corresponds to the test family referred to as "base", i.e., `./run_tests.py` is equivalent to `./run_tests.py base`. It runs all tests involving only required dependencies, if any.
