### ISSUE TITLE
developer/fuel_tank/double_tank.py is not working

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#116]
This example seems to get stuck when called with "python double_tank.py":
```
...
[INFO/Process-2]
 Working with partition cells: 206, 208
[WARNING/Process-2]      too small: si \cap Pre(sj), so discard intersection
[INFO/Process-2]         total # polytopes: 209
         progress ratio: 0.999977106751

[INFO/Process-2]
 Working with partition cells: 208, 208
[WARNING/Process-2]      too small: si \cap Pre(sj), so discard intersection
[INFO/Process-2]         total # polytopes: 209
         progress ratio: 1.0

Total abstraction time: 351.33[sec]
[INFO/Process-2] Total abstraction time: 351.33[sec]
Worker: Process-2finished.
[INFO/Process-2] process shutting down
```
Also, when I call it from within python (interactive mode), it gets back to the command prompt after a while without returning any `sys_ts` to the workspace. When I try to exit the interactive mode, I notice that one of the processes is indeed still running at the background.

**Comment by slivingston** [comment]
I was able to reproduce this error as of commit 1d465f76ea1907462d51444000adfa6a8d60b91c and am working on a fix now. For reference, an exception is raised if `double_tank.py` is modified to not use `multiprocessing`, e.g.,

```diff
--- a/examples/developer/fuel_tank/double_tank.py
+++ b/examples/developer/fuel_tank/double_tank.py
@@ -191,7 +191,8 @@ disc_params = {}
 disc_params[('normal', 'fly')] = {'N':N, 'trans_length':3}
 disc_params[('refuel', 'fly')] = {'N':N, 'trans_length':3}
 
-sys_ts = abstract.multiproc_discretize_switched(
+sys_ts = abstract.discretize_switched(
     ppp, switched_dynamics, disc_params, plot=False
 )
```

**Comment by slivingston** [comment]
The error arises because string literals are used without double quotation marks `"` in some parts of the specification formula.

**Comment by slivingston** [comment]
After adding `"`, a new error appears. It manifests as a `TypedDict` object being assigned a new value without first setting `allowed_values`. A temporary patch while I hunt for the origin is
```diff
--- a/tulip/transys/mathset.py
+++ b/tulip/transys/mathset.py
@@ -766,7 +766,7 @@ class TypedDict(dict):
     def __setitem__(self, i, y):
         """Raise ValueError if value y not allowed for key i."""
         valid_y = True
-        if i in self.allowed_values:
+        if hasattr(self, 'allowed_values') and i in self.allowed_values:
             valid_y = False
             if self.allowed_values[i] is None:
                 valid_y = True
```

**Comment by slivingston** [comment]
I cannot work on this anymore. To whomever wants to continue, note that the above error does not occur if `multiprocessing` is not used. E.g., try applying the patch in [my comment above](https://github.com/tulip-control/tulip-control/issues/116#issuecomment-86643298) to use `tulip.abstract.discretize_switched()` and notice that no error is raised regarding `TypedDict`.

**Comment by slivingston** [comment]
[multiprocessing.Queue](https://docs.python.org/2/library/multiprocessing.html#multiprocessing.Queue) uses pickling. Before commit 1c1ef990cfb042ec4984c9048dcd5c3644d70949, the class `TypedDict` could not be unpickled reliably, which was the last remaining cause of this issue.
