### ISSUE TITLE
encoding of Mealy machine states

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#137]
The states of the synthesized Mealy machines look a bit odd in the examples as of the head of master branch:
```
>>> print ctrl.states
States:
[u'0x9980E0',
 u'0x997D30',
 u'0x997F30',
 u'0x997F70',
 u'0x997C60',
 u'0x9978D0',
 'Sinit',
 u'0x997DC0',
 u'0x997E00',
 u'0x998210',
 u'0x9980A0',
 u'0x997B60']
```
Is this an intentional change or is this something to do with my setup?

**Comment by johnyf** [comment]
If you are using `gr1c`, then they appear normal, because it gives hexadecimal values to states, as in the example shown in [its documentation](http://slivingston.github.io/gr1c/md_formats.html).

**Comment by necozay** [comment]
I was just confused seeing different results in TuLiP in two different machines. Didn't notice this was due to different versions of `gr1c` installed on these machines. This seems to happen with `gr1c 0.9.0` but not with `gr1c 0.10.2`.

**Comment by johnyf** [comment]
Hexadecimal names strategy nodes result also with `gr1c == 0.11.0`.
