### ISSUE TITLE
place the examples under `examples/robot_planning/` directly under `examples/`

### ISSUE THREAD

**Issue by johnyf** [tulip-control/tulip-control#149]
Flat is better than nested. There is little reason to bury the examples so deep. Every time I want to open an example, I have to write "robot_planning", even though none of the two words is very descriptive of those examples.

If there are no objections, I will move these files.

**Comment by slivingston** [comment]
I agree with the proposed change. Because it only concerns examples, I think that it can go into version 1.2.1.

**Comment by johnyf** [comment]
Addressed with cce07057c85268bf97ffacde81b87a8283327b08.
