### ISSUE TITLE
Update MacPort download location, submit to MacPorts

### ISSUE THREAD

**Issue by johnyf** [tulip-control/tulip-control#15]
The [Portfile](https://github.com/tulip-control/tulip-control/blob/overhaul/contrib/macports/Portfile) needs updating to fetch `tulip` from its github repository, based on the release tag.

Next and after testing it, the Portfile needs to be [submitted](http://guide.macports.org/chunked/project.contributing.html) to the MacPorts project, so that they commit it to their repository.

**Comment by slivingston** [comment]
Following private communication with @johnyf, I am closing this issue. It is too much effort and too little benefit for us to maintain a MacPorts Portfile in addition to our other, preferred distribution media. There are already Portfiles for all of the difficult dependencies of TuLiP, namely [gr1c](https://trac.macports.org/browser/trunk/dports/math/gr1c/Portfile) and [cvxopt](https://trac.macports.org/browser/trunk/dports/python/py-cvxopt/Portfile). Thus, one good installation idiom on Mac OSX is
```sh
port install py27-cvxopt
port install gr1c
pip install tulip
```
