### ISSUE TITLE
Kernel Dies when prop2part function is called in continuous state robot motion planning example

### ISSUE THREAD

**Issue by hashim19** [tulip-control/tulip-control#208]
Hello everyone, 
I am trying to run continuous state robot motion planning example in Jupyter notebook. But when It tries to run Prop2part line in example, the kernel dies every time

#At this line
cont_partition = prop2part(cont_state_space, cont_props)
![kernel](https://user-images.githubusercontent.com/13851084/50571909-01276700-0dd7-11e9-95be-f7bce0f78131.png)

I search on the internet for the error and I found that it can be an issue with the jupyter notebook.
Then I try to run this example in spyder, and I guess it just hangs on the same line as above

#At this line
cont_partition = prop2part(cont_state_space, cont_props)

I am not able to figure out what can be a problem at my side, since I can see the example working on collab. 
![cont](https://user-images.githubusercontent.com/13851084/50571894-b279cd00-0dd6-11e9-9b80-b4b6bf87d18f.png)

Can it be a problem with my libraries?

**Comment by hashim19** [comment]
This error is solved now. I haven't installed cvxplot and glpk wasn't installed which was necessary for computing discrete abstractions from hybrid system descriptions.
Thanks

**Comment by slivingston** [comment]
happy it is solved.
