### ISSUE TITLE
syntax for initializing variables with a range of discrete values

### ISSUE THREAD

**Issue by abadithela** [tulip-control/tulip-control#211]
Hi, 

I am trying to implement an example similar to the Discrete State Robot Motion Planning example given [here](https://tulip-control.sourceforge.io/doc/tutorial.html). My example has a bigger gridworld with an additional moving obstacle that the system is trying to avoid while it continually reaches its goal states. Right now, I'm initializing each grid cell as a state for both the system and the obstacle. I know that there is a better way to do this -- variables don't have to just be Boolean but they can hold a range of discrete values. However, I'm not sure how the syntax works for this. For example, do I instantiate env variables with discrete values like this: env_vars = {'obs' : {'1', '2', '3'}}? 

Thanks!

**Comment by murrayrm** [comment]
@johnyf @slivingston I thought I remembered there was a way to do this, but can't find  anything in the documentation (?).  Perhaps this was something that `omega` supported?

**Comment by necozay** [comment]
See line 63 in:

https://github.com/tulip-control/tulip-control/blob/master/examples/gr1_set.py

**Comment by abadithela** [comment]
Thanks everyone!

**Comment by slivingston** [comment]
@abadithela is your question therefore answered?

**Comment by slivingston** [comment]
while we wait for confirmation from @abadithela , I recommend that the task of this ticket is to revisit documentation and decide how easily someone with this question in the future can find an answer.

**Comment by abadithela** [comment]
Hi Scott, my question has been answered. Sorry for the delay.
