### ISSUE TITLE
redundancy in jtlv output

### ISSUE THREAD

**Issue by slivingston** [tulip-control/tulip-control#27]
(Copied from https://sourceforge.net/p/tulip-control/bugs/12/ with creation date 2011-12-30.  Assigned to Ufuk Topcu there.)

Sometimes jtlv generated automaton has redundant transitions. Couple of examples:

robot\_discrete\_simple:
State 14 with rank 0 -&gt; &lt;park:0, cellID:0, X0reach:0&gt;
With successors : 15, 16, 15, 16

transitions 14-&gt;15 and 14-&gt;16 are both repeated.

Similar behavior in robot\_discrete\_simple2:
State 31 with rank 0 -&gt; &lt;park:0, cellID:0, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 32 with rank 0 -&gt; &lt;park:0, cellID:4, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 33 with rank 0 -&gt; &lt;park:0, cellID:1, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 34 with rank 0 -&gt; &lt;park:0, cellID:5, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 35 with rank 0 -&gt; &lt;park:1, cellID:0, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 36 with rank 0 -&gt; &lt;park:1, cellID:4, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 37 with rank 0 -&gt; &lt;park:1, cellID:1, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 38 with rank 0 -&gt; &lt;park:1, cellID:5, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 39 with rank 0 -&gt; &lt;park:0, cellID:2, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 40 with rank 0 -&gt; &lt;park:0, cellID:3, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12
State 41 with rank 0 -&gt; &lt;park:1, cellID:2, ccellID:0, gear:1&gt;
With successors : 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12

I haven't experienced any particular problem on python side due to this "bug". However, it would be useful to understand the reasons causing this behavior on java side and to identify its implications on python side.

**Comment by johnyf** [comment]
As of `tulip == 1.2.0`, the solver `jtlv` is not used any more, is unmaintained, and being replaced by `gr1c` and `omega`. So, this issue can be closed.
