### ISSUE TITLE
Bisimulation algorithm in transys 

### ISSUE THREAD

**Issue by slivingston** [tulip-control/tulip-control#28]
(Copied from https://sourceforge.net/p/tulip-control/feature-requests/27/ with creation date 2013-07-11.)

Bisimulation algorithm for transition systems as a way for simplifying transition systems.
Suggested: Alg. 32, p.482 [Baier], not decided yet. Possibly interesting a version that takes into account actions.

**Comment by necozay** [comment]
done  in 19da152d868914da475428839481d64bb6acaadc (see  https://github.com/tulip-control/tulip-control/blob/ce54897c242689f45ad33650f157bf1805b35ed6/tulip/transys/transys.py#L863).
