### ISSUE TITLE
Add a method to call the tool HARE

### ISSUE THREAD

**Issue by slivingston** [tulip-control/tulip-control#31]
(Copied from https://sourceforge.net/p/tulip-control/feature-requests/23/ with creation date 2012-06-07, by Pavithra Prabhakar)

Add a method to call the tool HARE, which does model-checking of rectangular hybrid automata and returns counter-examples.

**Comment by johnyf** [comment]
Should this issue be closed as "wontfix" ?

**Comment by slivingston** [comment]
I agree, but I would instead describe it as a low-priority, entirely independent feature request for which there are no plans to implement. It might be of interest later.

However, to avoid creating yet another label, "wontfix" is OK.
