### ISSUE TITLE
variable length reachability

### ISSUE THREAD

**Issue by slivingston** [tulip-control/tulip-control#40]
(Copied from https://sourceforge.net/p/tulip-control/feature-requests/6/ with creation date 2012-02-22.)

In the current abstraction methods when we establish reachability relations, we look for reachability in exactly `N` steps. It is possible to add an option for reachability in up to `N` steps. This information is already computed in closed-loop algorithm, just needs some book-keeping to make it available as an abstraction option (e.g. within a cell in the partition, we need to know which parts reach in how many steps).

COMMENTS from https://sourceforge.net/p/tulip-control/feature-requests/6/:

2012-02-23 by Nok Wongpiromsarn: Actually, in the MATLAB implementation, this is done by default. (It looks for reachability up to `N` steps instead of exactly `N` steps.) There is a parameter `Options.useAllHorizonLength` that you can set when you call the `discretize` function whether you want reachability up to `N` steps (`Options.useAllHorizonLength=true`) or exactly `N` steps (`Options.useAllHorizonLength=false`).

2012-02-23 by anonymous: Thanks for the heads-up Nok! Good to know what is available ;) I just noticed that we have that option in Python as well but, as far as I can tell, the missing part is online input calculation for this type of abstraction.

**Comment by slivingston** [comment]
@johnyf Why did you label this as a "bug"?

**Comment by necozay** [comment]
I suggest shifting the milestone for this issue to a later release. It is probably better to address this when we include more continuous/hybrid closed loop simulation functions (i.e., together with issue #60)

**Comment by johnyf** [comment]
We have had some correspondence with @slivingston about the issues that I had noted in an old email. We decided, as suggested, to address this in the future, and also transfer a comprehensible description here, from that email.

**Comment by slivingston** [comment]
There are also the following action-items, which I will now do in time for inclusion in v1.2.0:

1. Add note in docstring that the case of `use_all_horizon=True` is
still under development and currently unavailable.

2. Raise ValueError if user attempts to call discretize() or any
function in tulip/abstract/feasible.py with `use_all_horizon=True`.

**Comment by slivingston** [comment]
Both of the above action-items are done as of 430567b026f9639d874dfbd93e2c5375bec4883b.

**Comment by johnyf** [comment]
Based on:

- PEP20: flat is better than nested,
- the [Unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy): build sharp tools that do one thing well,
- [Knuth](http://dx.doi.org/10.1145/356635.356640): avoid premature optimization, and
- personal experience,

Nesting the labeling of subpartitions (or other mechanism) outlined [above](https://github.com/tulip-control/tulip-control/issues/40#issuecomment-37120298) within a discretization algorithm is unlikely to be dependable or easy to maintain.

We can distinguish two use cases mentioned above:

1. abstract (prove that we can concretize later, etc.)
2. use the result (be it for simulation or real-life actuation).

Viewing `tulip` roughly as a compiler toolchain, abstraction need only concern itself with proving the mathematical statement that it does now.

The primary purpose of labeling states in a cell with individual horizons applicable there is optimization (and it increases the complexity of the data structure too), so it would better be performed as a separate, post-processing step that happens before simulation, and before deployment of a controller.

As of c3724772fb3e720fa427f9a082f5593dfda3d214, the main issue mentioned in the OP has been addressed, and the remaining tasks are delegated to #162
