### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by johnyf** [tulip-control/tulip-control#44]
All the required dependencies work in Python 3. Ports `py33-numpy`, `py33-scipy`, `py33-networkx`, `py33-parsing` already exist in MacPorts. Although subport `py27-cvxopt` exists but no `py33-cvxopt` subport, as [noted](http://cvxopt.org/install/index.html) in `cvxopt`'s site it works in Python 3.x, so it should be mostly a matter of updating its macport.

Given the above, `tulip` can be ported to Python 3. A side-by-side comparison between Python 2 and 3 can be [read here](http://ptgmedia.pearsoncmg.com/imprint_downloads/informit/promotions/python/python2python3.pdf).

**Comment by johnyf** [comment]
[PEP373](https://www.python.org/dev/peps/pep-0373/) sets the end of Python 2 support to 2020.

**Comment by johnyf** [comment]
The time has come, [planned Python 2 releases](http://legacy.python.org/dev/peps/pep-0373/#maintenance-releases) reach their end this coming Sun:

- 2.7.12 2016-06-25
- beyond this date, releases as needed

I think that it is time to stop using Python 2.

**Comment by slivingston** [comment]
Thanks for the notification. As implied by some of your comments above, we cannot simultaneously implement both in Python 2 and 3. I recommend after the forthcoming release that we concentrate on Python 3 and provide some backwards support, e.g., using [six](https://pypi.python.org/pypi/six).

**Comment by johnyf** [comment]
I strongly recommend porting to Python 3 without worrying about Python 2, and trying to support Python 2 afterwards. If too difficult (I expect it will be easy), then no good reason to invest effort in Python 2. Whoever needs Python 2 can use versions up to 1.2.1.

We could use the `futurize` script provided by the package [`future`](https://github.com/PythonCharmers/python-future), instead of `six`:

"`python-future` is a higher-level compatibility layer than `six` that includes more backported functionality from Python 3, more forward-ported functionality from Python 2, and supports cleaner code, but requires more modern Python versions to run."

(quote [from here](http://python-future.org/faq.html#what-is-the-relationship-between-future-and-six))

As suggested in this [blog post from Jan 03, 2013](https://jakevdp.github.io/blog/2013/01/03/will-scientists-ever-move-to-python-3/) with an update note at the top: "March 2016: ... Short version: just use Python 3. There's almost no reason not to any more." I agree with that, because I can see only 2 reasons not to:

1. reinstalling python: this is easy. Clone [`cpython`](https://github.com/python/cpython), checkout branch 3.5, compile, install, and edit `~/.bashrc`. Shouldn't take more than a few minutes, modulo `apt get-install`. Works well on both Linux and OS X, provided that you use the system compiler and libraries in OS X (i.e., remember to hide MacPorts' paths when compiling python).

2. porting your own code: [`2to3`](https://docs.python.org/2/library/2to3.html) should work quite well for user scripts.

Other packages that we may find useful: [`modernize`](https://github.com/mitsuhiko/python-modernize) and [`caniusepython3`](https://github.com/brettcannon/caniusepython3).

**Comment by slivingston** [comment]
@johnyf Thanks for your arguments. You assigned this issue to yourself, but I am also available to work on moving TuLiP to Python 3. Tell me how I can be useful, or allocate tasks to me.

**Comment by slivingston** [comment]
The rules for inheritance of the `__hash__` method have changed from versions 2.7 to 3.5, causing a TypeError exception of unhashable type from the following code:
```python
import tulip.spec.ast

nodes = tulip.spec.ast.make_fol_nodes()
x = nodes.Var('x')
print(hash(x))
```
whereas on Python 2.7, a hash value is obtained. Before running the above code is feasible on Python 3, several small modifications are necessary, e.g., replacing `isinstance` checks from `basestring` to `str`. However, these are not relevant for the issue of hash value.

The main change in the Python language specification is found in the following parts:
* [from the description of `__hash__` for Python 2.7](https://docs.python.org/2.7/reference/datamodel.html#object.__hash__): "Classes which inherit a `__hash__()` method from a parent class but change the meaning of `__cmp__()` or `__eq__()`...can explicitly flag themselves as being unhashable by setting __hash__ = None in the class definition."
* [from the description of `__hash__` for Python 3.5](https://docs.python.org/3.5/reference/datamodel.html#object.__hash__): "A class that overrides `__eq__()` and does not define `__hash__()` will have its `__hash__()` implicitly set to None."

Notice the change from "can explicitly" to "will implicitly".

**Comment by slivingston** [comment]
Hash values are necessary for using AST nodes in `networkx` graphs. The only required property of hash values is that for any two objects A and B,

    A = B => hash(A) = hash(B)

**Comment by slivingston** [comment]
[The `Var` class](https://github.com/tulip-control/tulip-control/blob/5d161c0ee74020b80c320f119c15a325d6d34a39/tulip/spec/ast.py#L245) obtained from `tulip.spec.ast.make_fol_nodes()` derives from `Terminal`, which in turn derives from `Node`, which is an abstract base class. The change in the Python language specification affects the `Terminal` class because `__eq__` is defined for it, but `__hash__` is not defined.

To make `Terminal` and derived classes hashable, I propose to define `__hash__` as the hash of the string representation of `Terminal`, i.e.,
```python
def __hash__(self):
    return hash(self.__repr__())
```
where `__repr__` is defined [on lines 134-136 of ast.py](https://github.com/tulip-control/tulip-control/blob/5d161c0ee74020b80c320f119c15a325d6d34a39/tulip/spec/ast.py#L134-L136) as on the current tip of `master` branch.

**Comment by johnyf** [comment]
Thanks for reasoning about this hashability issue. As remarked, we do need to make AST nodes hashable, if we want to use `networkx` for graph transformations. The below assumes that using `networkx` is necessary (I implemented it, and I have counter-arguments now, but that is another discussion).

Due to the comment on [these lines](https://github.com/tulip-control/tulip-control/blob/5d161c0ee74020b80c320f119c15a325d6d34a39/tulip/spec/ast.py#L88) of the `Node` ABC introduced in https://github.com/tulip-control/tulip-control/commit/5c811597ed84b5c56ca952b51c2bcfb11d620dcb#diff-719aec8a13db4b5e790fd8601cc6aa03R421:

```python
        # Caution
        # =======
        # Do **NOT** implement C{__hash__}, because you
        # will unintendently identify different AST nodes !
        # Only leaf nodes can be safely identified.
        #
        # The default for user-defined classes is
        # C{__hash__ == _}
```

I will revisit the possible cases:

If `__hash__` is implemented for the `Node` ABC, and isn't overridden, of course we identify terminals with operators etc, so apples with oranges. But there is a subtler issue to consider.

Even when we have two terminal nodes that are for all purposes identical, say two different instances `Var('x')` and `Var('x')`, then if these have the same hash value, then in a `dict` they represent the same element. `networkx` uses a `dict`-of-`dict`-etc. to store nodes. So, all *different* occurrences of the symbol `"x"` in a formula string will be identified as the same AST node.

If we allowed this for operator nodes, we could get cycles in the graph of the abstract syntax tree. If we defined hash values in this way (i.e., based on `repr`) only for terminals, then the tree can become an acyclic graph, but we won't get cycles.

For substitutions, it seems to me that a DAG would still work. But I am unsure whether other manipulations of the AST, or analysis will remain possible. It seems to me that context-sensitive syntactic manipulation (e.g., substitute occurrences of `"x"` in the scope of one quantifier, but not of another quantifier) won't be possible if we let terminals be identified by their `repr`.

For these reasons, I recommend defining `__hash__` in the same way as Python 2 defines it by default: using `id`. With this definition different occurrences of each terminal in a formula are still represented by different nodes in the `networkx` graph for the AST.

```python
def __hash__(self):
    return id(self)
```

A side-benefit is that there also won't be a change in API behavior (in the sense of what `__hash__` evaluates to).


### History

A method `Operator.__hash__` appears to have sneaked in the code in the same commit that warns against defining `__hash__` (here: https://github.com/tulip-control/tulip-control/commit/5c811597ed84b5c56ca952b51c2bcfb11d620dcb#diff-719aec8a13db4b5e790fd8601cc6aa03R507). The commit message comments on using the default `id` as hash value. Later, this `__hash__` method was removed (here: https://github.com/tulip-control/tulip-control/commit/396aca1a0d05424c571ef8194fd20918fddbf125#diff-719aec8a13db4b5e790fd8601cc6aa03L516), though the commit message seems oblivious of the consequences of its presence up to that point. Instead, it remarks "do not use custom __hash__: too slow".


### Aside

I happened to run into another issue with `__hash__` that is the same in both Python 2 and 3: user-defined classes are hashable using `id` by default, but if they define any comparator method (e.g., `__richcmp__`) without defining a `__hash__` method, then they become unhashable. In the case of `dd.cudd.Function` objects (and their counterparts in modules that implement the same interface), I implemented a `__hash__` not too long ago (https://github.com/johnyf/dd/commit/0b29f9f7699e6a1b4ef921917300969d7ea9a3cf).
