### ISSUE TITLE
Sort out what version of numpy (and other packages) to require for TuLiP

### ISSUE THREAD

**Issue by murrayrm** [tulip-control/tulip-control#48]
As part of commit ce7d868, we bumped the requirement for NumPy up to 1.7+.  Some stable distributions of linux (and Mac OS X?) use NumPy 1.5.  We should decide what we want to support.  Opening this issue to create a place for discussion.

**Comment by slivingston** [comment]
As of da82dcb0fa047dbdca3b5cfd625ee2f5b82700cf, there is a requirements.txt file that lists known working and current versions of Python dependencies. In the installation page of the User's Guide, at least version 0.9.0 of gr1c is requested. The required versions of other external tools are not documented, but I think it is enough to say try the most recent and then document known failures as they are discovered.
