### ISSUE TITLE
How to use the controller synthesized by TuLiP?

### ISSUE THREAD

**Issue by wmgithub** [tulip-control/tulip-control#66]
I am quite new to TuLiP, and my goal is to synthesize a reactive controller using TuLiP and do a simulation elsewhere. Now I managed to get the controller as an instance of `MealyMachine` class (using `synth.synthesize('gr1c', specs, sys))`, but how can I use it in other places? For example, given (possibly, a list of) values to input variables,  how do I get the output from the controller? Doing manual simulations certainly will not work in this case. 
Thanks!

**Comment by psraditya** [comment]
If I try to print the controller generated using gr1c I see the input and output set of states but don't see anything under transitions and labels. Why is it so?

**Comment by johnyf** [comment]
Can you please elaborate on:

1. version or commit hash of repository used
2. the controller generated using `gr1c` as an instance of a `networkx` graph, or a Mealy transducer ?
3. for which specification: a minimal working example would help

For instance, the string representation of a Mealy transducer is created [here](https://github.com/tulip-control/tulip-control/blob/ef67131ee362be0d984f4cb84a7d56d31f7447b4/tulip/transys/machines.py#L425).
