### ISSUE TITLE
continuous.py stalls with cvxopt native solver

### ISSUE THREAD

**Issue by necozay** [tulip-control/tulip-control#82]
When not using `glpk`, the example `continuous.py` seems to stall. I've waited about 40 minutes, then I gave up. It seems to work fine if I increase the input bound to 5. Possibly related to #23 and #73.

**Comment by slivingston** [comment]
I tried to run `examples/continuous.py` today as of the current tip of `master` branch (commit 5d161c0ee74020b80c320f119c15a325d6d34a39), using each of the currently available solver configurations. For 1 trial, durations of abstraction process in seconds:

* GLPK solver, wrapped by CVXOPT: 8
*  conelp() function of CVXOPT (not using GLPK): 131
* SciPy solver, `scipy.optimize.linprog`: 94

Test was on Debian GNU/Linux 8.7 with

* Python 2.7.9
* networkx 1.10
* numpy 1.11.2
* scipy 0.18.1

**Comment by slivingston** [comment]
Because this issue is old and, currently, I cannot replicate the originally reported behavior, I am closing this issue. @necozay or anyone can re-open if they are still observing it.
