### ISSUE TITLE
matplotlib considered harmful

### ISSUE THREAD

**Issue by johnyf** [tulip-control/tulip-control#94]
Yes it is me saying this... according to `cProfile`, `matplotlib` consumes an embarrassing amount of time to load itself. The result: every run, however irrelevant plotting might be for it, loads `matplotlib` and thus cannot run faster than a fixed minimal amount of time (on average).

These effects can be avoided by loading `matplotlib` only in plotting functions, *not* at the top of files. For example saving digraphs is independent of `matplotlib`, so only `pydot` suffices there. It seems that `matplotlib` may be entirely avoidable there, using some [`ipython` magic for `graphviz`](https://gist.github.com/cjdrake/7982333).

Also, `tulip.__init__` loads every subpackage, which causes all of `abstract` and `hybrid` to be loaded, even if one only desires to work with discrete systems (e.g., with `synth`, `interfaces`, and `transys`).

Arguably, only hybrid systems work justifies loading `abstract` and `matplotlib`, because:
- this is where `matplotlib` plotting capabilities are used
- the time typically consumed by abstraction reduces the relative overhead of loading `matplotlib`.

**Comment by slivingston** [comment]
To support "it is suggested that this convention..." [above](https://github.com/tulip-control/tulip-control/issues/94#issuecomment-52112823), I wrote the recommendation under [Inline imports](https://github.com/tulip-control/tulip-control/wiki/Drafts-of-code-conventions#inline-imports) on the [Drafts of code conventions](https://github.com/tulip-control/tulip-control/wiki/Drafts-of-code-conventions) page of [the dev wiki](https://github.com/tulip-control/tulip-control/wiki).

**Comment by slivingston** [comment]
All of the import lines in `tulip/transys/export/__init__.py` were commented-out and have been so for a while, so I deleted them in c8f821793035660b910e586cff625092193deb79
