### ISSUE TITLE
tulip LTL syntax for arbitrary finite types is ambiguous

### ISSUE THREAD

**Issue by johnyf** [tulip-control/tulip-control#99]
Consider a variable that is not a Boolean nor an integer, but can take values from an arbitrary finite domain. Currently such domains are allowed to be represented in tulip using "names" in the formula ("names" refers to the production rule in the PLY parser generator). This is exactly the same as the syntax for variable references.

So within an LTL formula it is impossible to distinguish variables from *values* taken by variables. This is:
- ambiguous
- requires a definition of variable types extraneous to the formula even for deciding what is a variable reference and what is a constant
- is fragile: it allows reusing the same literal for both a variable and its value (or a variable and the value of another variable - with the same consequences) as in #96. Checks to prevent this from happening have been introduced in 45a85ebdfe9031655b7e310d20df9215b709e7b1. But still, this is a weak solution.

A change is needed to avoid such situations. It is proposed that *constants* be introduced in the syntax, enclosed in double quotes. For example, instead of writing `loc=up` this should become `loc="up"`. So `loc=up` can no more be misinterpreted as the equality of two variables, and conversely, if used it has a unique interpretation, as an equality comparison between two variables.

Sidenote: currently equality testing between variables is not supported by `gr1c`, but it may be by `jtlv`. So this syntax will clearly distinguish between the two cases, w/o the need to restrict the current parser or infer things ad hoc after parsing (or wait for the user to manually check for absence of conflicts globally in the problem statement: this is tough for anyone not familiar with the naming of auxiliary variables that are automatically introduced within `synth`.

The change above has already been implemented in the context of ongoing work to rewrite part of `synth` (and a bit of `interfaces.gr1c`) to:

- allow integer states in transition systems (#77)
- replace the current syntactic substitutions as an evaluation mechanism of formulas in `GRSpec` with a dependable substitution in the AST instead
- handle robustly constant and variable name conflicts as outlined above
- improve the code of AST classes (including their names) and introduce `networkx` functionality for easy manipulation of the AST
- address spurious non-determinism wrt machine memory (#93)
- address #86

Other motivation for introducing the syntax (that actually was the starting point that motivated the double quotes) is using python's own `eval`. This will allow substituting values for variables in the AST, then flattening to python representation and applying `eval`. Using the same syntax for constants as python strings, the substitution of `loc` in `loc="up"` will yield the AST corresponding to `"up"="up"` and then flattening to python yields `"up" == "up"`, which evaluates to `True`.

**Comment by slivingston** [comment]
For posterity, I ran the timing script [above](https://github.com/tulip-control/tulip-control/issues/99#issuecomment-53971202) against c7be6b7a85801324ea243689985043e823a5fc69 on Python 2.7.6 and Ubuntu 14.04 with Linux x86_64 running on 2.40GHz Intel Core i7 and obtained similar ratios of times, thus supporting the conclusions above.

When I run the small script `test_double_quotes.py` [above](https://github.com/tulip-control/tulip-control/issues/99#issuecomment-53973067) demonstrating this issue against `master` branch (tip is c8f821793035660b910e586cff625092193deb79 at time of writing), the output is instead

```shell
Traceback (most recent call last):
  File "test_double_quotes.py", line 9, in <module>
    mealy = synth.synthesize('gr1c', spc)
  File "tulip/synth.py", line 1089, in synthesize
    strategy = gr1c.synthesize(specs)
  File "tulip/interfaces/gr1c.py", line 410, in synthesize
    s = translate(spec, 'gr1c')
  File "tulip/spec/translation.py", line 324, in translate
    spec.str_to_int()
  File "tulip/spec/form.py", line 614, in str_to_int
    a = self.ast(x)
  File "tulip/spec/form.py", line 641, in ast
    self.parse()
  File "tulip/spec/form.py", line 663, in parse
    tx.check_for_undefined_identifiers(g, vardoms)
  File "tulip/spec/transformation.py", line 198, in check_for_undefined_identifiers
    ', in subformula:\n\t' + str(tree))
ValueError: undefined variable: c, in subformula:
	Abstract syntax tree as graph with edges:
[('(= a b)', 'b'), ('(= a b)', 'a'), ('(= a c)', 'a'), ('(= a c)', 'c'), ('(| (= a b) (= a c))', '(= a c)'), ('(| (= a b) (= a c))', '(= a b)')]
```

where the path prefix above the repository level is stripped. Note that this is distinct from that reported [above](https://github.com/tulip-control/tulip-control/issues/99#issuecomment-53973067). Modifying the `sys_safe` definition in the original script to be

```python
sys_safe = ['(a = b)']
```

leads to

```shell
                               gr1c return code: 255

                               gr1c stdout, stderr:
 syntax error, unexpected VARIABLE, expecting NUMBER
Error detected on line 8.



Traceback (most recent call last):
  File "test_double_quotes.py", line 9, in <module>
    mealy = synth.synthesize('gr1c', spc)
  File "tulip/synth.py", line 1095, in synthesize
    ctrl = strategy2mealy(strategy, specs)
  File "tulip/synth.py", line 1207, in strategy2mealy
    mach.states.add_from(A)
  File "tulip/transys/labeled_graphs.py", line 175, in add_from
    self.graph.add_nodes_from(new_states, check, **attr)
  File "tulip/transys/labeled_graphs.py", line 900, in add_nodes_from
    for n in nodes:
TypeError: 'NoneType' object is not iterable
```

where again path prefixes were stripped. It seems that the `c` is caught before the `b` in the implementation at c8f821793035660b910e586cff625092193deb79 (tip of `master` at time of writing). In any case, the lesson is that the example formula is ambiguous, and thanks to recent extensions by @johnyf, this ambiguity can be resolved using double quotation marks.
